name: My first github action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4              # for actions use "uses"    

        - name: Welcome message
          run: echo "Welcome to Github Actions"  # for task use "run"
        
        - name: List files in directory
          run: ls 

        - name: Run multiple command in single task
          run: |                                  # To run multiple commands use pipe
             echo "Task to run multiple commands in single task"
             ls -ltra
             cat README.md