name: My first github action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4              # for actions use "uses"    

        - name: Welcome message
          run: echo "Welcome to Github Actions"  # for task use "run"
        
        - name: List files in directory
          run: ls 