name: My first github action

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "Welcome to Github Actions"
        
    second_job:
        runs-on: ubuntu-latest
        steps:
        - name: List files in directory
          run: ls