name: Workflow to run multiple jobs

on: 
    push

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Job_1
          run: echo "This is first job"

    job_2: 
        needs: job_1
        runs-on: ubuntu-latest
        steps:
        - name: Job_2
          run: echo "This is second job"

    job_3:
        needs: [job_1, job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Job 3
          run: echo "This is third job"