name: Workflow to Execute shell script

on:
    push

jobs:
    script_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4  
          
        - name: List files
          run: ls -ltra ./.github/workflows

        - name: Execute shell script
          run: |
              chmod +x ./.github/workflows/print_num.sh    
              ./.github/workflows/print_num.sh