name: Workflow to Execute shell script

on:
    push

jobs:
    script_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4  
          
        - name: List files
          run: ls -ltra

        - name: Execute shell script
          run: |
              chmod +x print_num.sh           
              ./print_num.sh